# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', '\u8349\u7a3f'), ('public', '\u516c\u5f00')], default='draft', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('mail', models.EmailField(max_length=254)),
                ('sex', models.CharField(choices=[('M', '\u7537'), ('F', '\u5973')], max_length=2)),
                ('age', models.IntegerField(max_length=2)),
                ('sign', models.TextField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='textinfo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textinfo', to='blog.User'),
        ),
    ]
