# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170913_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=2),
        ),
    ]
