# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170913_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', '\u7537'), ('F', '\u5973')], max_length=2),
        ),
    ]
